#!/bin/sh

/usr/bin/invoke_app "$@" -C "start_jupyter -T @tool tellurium.ipynb" \
                        -t tellurium \
                        -u anaconda3-5.1 \
                        -e TOOL_PYTHONPATH=/apps/share64/debian7/anaconda/anaconda3-5.1/tools/tellurium/20190823/lib/python3.6/site-packages